### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by doyu** [njlabo/matmul-comparison#1]
At first, investigate SOTA.

- [x] Prepare for test calculation of matrix multiplications + accumulations, ~1min.
- [x] Implement test-all.py to accomodate the following all cases.
- [x] Measure with Pytorch.
- [x] Measure vanila matmul.
- [x] Measure with OMP.
- [x] Measure with external matmul library.
- [ ] Add BLAS support for Linux
- [ ] Present the comparison data.

ETA: 30h
